### ISSUE TITLE
General question about user input.

### ISSUE THREAD

**Issue by Caesurus** [ChrisTheCoolHut/PinCTF#1]
I'm curious how i would be able to specify which user input I want to test. Say for instance I have an application that takes a Name, Email, and Key. And Name and Email are used in the generation of Key. I know what I want Name and Email to be (they are specified in the challenge), and Key is in a known format, EG: 1111-2222-3333-4444-5555-6666, how would I go about using pinCTF.

**Comment by ChrisTheCoolHut** [comment]
By default PinCTF has two test modes. It will test an argument being passed in on the commandline and STDIN being sent into a program. If your binary accepts input through those you could modify the "COMMAND" argument being passed into the program to add those values into it.

**Comment by Manouchehri** [comment]
Is there way to choose if stdin or an arg should be used?
