### ISSUE TITLE
Threading problem

### ISSUE THREAD

**Issue by sln-1550** [ChrisTheCoolHut/PinCTF#16]
When I use pinCTF with open threading, the error occupied.
./pinCTF.py -f myprogram  -a -sl 28 -t -tc 4
[~] Status:
threading : True
reverseRange : False
skipFavoredPaths : False
c had exception [Errno 2] No such file or directory: 'pin_c/inscount.out'
b had exception [Errno 2] No such file or directory: 'pin_b/inscount.out'
a had exception [Errno 2] No such file or directory: 'pin_a/inscount.out'
d had exception [Errno 2] No such file or directory: 'pin_d/inscount.out'
e had exception [Errno 2] No such file or directory: 'pin_e/inscount.out'
g had exception [Errno 2] No such file or directory: 'pin_g/inscount.out'
h had exception [Errno 2] No such file or directory: 'pin_h/inscount.out'
f had exception [Errno 2] No such file or directory: 'pin_f/inscount.out'
i had exception [Errno 2] No such file or directory: 'pin_i/inscount.out'
j had exception [Errno 2] No such file or directory: 'pin_j/inscount.out'
k had exception [Errno 2] No such file or directory: 'pin_k/inscount.out'
l had exception [Errno 2] No such file or directory: 'pin_l/inscount.out'
m had exception [Errno 2] No such file or directory: 'pin_m/inscount.out'
n had exception [Errno 2] No such file or directory: 'pin_n/inscount.out'
o had exception [Errno 2] No such file or directory: 'pin_o/inscount.out'
p had exception [Errno 2] No such file or directory: 'pin_p/inscount.out'
q had exception [Errno 2] No such file or directory: 'pin_q/inscount.out'
.......

pls help me, thanks.

**Comment by ChrisTheCoolHut** [comment]
Once I get time, I'll do a real fix. If you're looking to get it working right away, use a full path for the `-f` flag.

The example in the readme shows:

```
./pinCTF.py -f $(pwd)/examples/crypt4 -a -sl 26 --threading -tc 4
```

So I would think you could do
```
./pinCTF.py -f $(pwd)/myprogram -a -sl 28 -t -tc 4

```

**Comment by sln-1550** [comment]
sorry for late reply.
Your command is still not working, I tried both absolute path from root and $pwd, but failed, even copy myprogram to pinCTF's main directory.
![image](https://user-images.githubusercontent.com/59176056/92338609-0d071880-f0e4-11ea-8db6-443fa909b332.png)
![image](https://user-images.githubusercontent.com/59176056/92338688-961e4f80-f0e4-11ea-9e92-d2c3b944edd1.png)

**Comment by ChrisTheCoolHut** [comment]
`./pinCTF.py -f $(pwd)/xx_warmup_obf -sl 28 -st 5 -t -tc 4 -sk -s flag{xxxxxxxxxxxxxxxxxxxxxx} -l $(pwd)/obj-intel64 -i -r 0123456789abcdefg_Fl`

You need the absolute path to the pin lib folder too.
`$(pwd)/obj-intel64 `

**Comment by sln-1550** [comment]
I got it, thank you.
