### ISSUE TITLE
Getting this error when running the script

### ISSUE THREAD

**Issue by neomh** [ChrisTheCoolHut/PinCTF#6]
sudo python3.6 pinCTF.py -f $(pwd)/examples/ELF-NoSoftwareBreakpoints -i -sl 25 -rev
-t -tc 4 -r abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890_-@
[~] Status:
threading : True
reverseRange : True
skipFavoredPaths : False
[~] Running in reverse direction
sh: 1: /pin: not found
sh: 1: c had exception [Errno 2] No such file or directory: 'pin_c/inscount.out'
/pin: not found
sh: 1: /pin: not foundsh: 1:
/pin: not found
b had exception [Errno 2] No such file or directory: 'pin_b/inscount.out'
d had exception [Errno 2] No such file or directory: 'pin_d/inscount.out'
a had exception [Errno 2] No such file or directory: 'pin_a/inscount.out'
sh: 1: /pin: not found
sh: 1: /pin: not found
e had exception [Errno 2] No such file or directory: 'pin_e/inscount.out'
sh: 1: /pin: not found
f had exception [Errno 2] No such file or directory: 'pin_f/inscount.out'
h had exception [Errno 2] No such file or directory: 'pin_h/inscount.out'
sh: 1: /pin: not found
g had exception [Errno 2] No such file or directory: 'pin_g/inscount.out'
sh: 1: /pin: not foundsh: 1:
/pin: not found
sh: 1: /pin: not found
j had exception [Errno 2] No such file or directory: 'pin_j/inscount.out'
sh: 1: /pin: not found
i had exception [Errno 2] No such file or directory: 'pin_i/inscount.out'
k had exception [Errno 2] No such file or directory: 'pin_k/inscount.out'
l had exception [Errno 2] No such file or directory: 'pin_l/inscount.out'
sh: 1: /pin: not found
sh: 1: sh: 1: /pin: not found/pin: not found

m had exception [Errno 2] No such file or directory: 'pin_m/inscount.out'
o had exception [Errno 2] No such file or directory: 'pin_o/inscount.out'
n had exception [Errno 2] No such file or directory: 'pin_n/inscount.out'
sh: 1: /pin: not found
p had exception [Errno 2] No such file or directory: 'pin_p/inscount.out'
sh: 1: /pin: not foundsh: 1:
/pin: not found
s had exception [Errno 2] No such file or directory: 'pin_s/inscount.out'
q had exception [Errno 2] No such file or directory: 'pin_q/inscount.out'
sh: 1: /pin: not found
sh: 1: /pin: not found
r had exception [Errno 2] No such file or directory: 'pin_r/inscount.out'
t had exception [Errno 2] No such file or directory: 'pin_t/inscount.out'
sh: 1: /pin: not foundsh: 1:
/pin: not found
v had exception [Errno 2] No such file or directory: 'pin_v/inscount.out'
sh: 1: /pin: not found
u had exception [Errno 2] No such file or directory: 'pin_u/inscount.out'
w had exception [Errno 2] No such file or directory: 'pin_w/inscount.out'
sh: 1: /pin: not found
x had exception [Errno 2] No such file or directory: 'pin_x/inscount.out'
sh: 1: /pin: not found
A had exception [Errno 2] No such file or directory: 'pin_A/inscount.out'
sh: 1: /pin: not found
y had exception [Errno 2] No such file or directory: 'pin_y/inscount.out'
sh: 1: /pin: not found
z had exception [Errno 2] No such file or directory: 'pin_z/inscount.out'
sh: 1: /pin: not found
B had exception [Errno 2] No such file or directory: 'pin_B/inscount.out'
sh: 1: /pin: not found
C had exception [Errno 2] No such file or directory: 'pin_C/inscount.out'
sh: 1: /pin: not found
sh: 1: /pin: not found
D had exception [Errno 2] No such file or directory: 'pin_D/inscount.out'
sh: 1: /pin: not found
E had exception [Errno 2] No such file or directory: 'pin_E/inscount.out'
F had exception [Errno 2] No such file or directory: 'pin_F/inscount.out'
sh: 1: /pin: not found
G had exception [Errno 2] No such file or directory: 'pin_G/inscount.out'
sh: 1: sh: 1: /pin: not foundsh: 1: /pin: not found
/pin: not found

H had exception [Errno 2] No such file or directory: 'pin_H/inscount.out'
J had exception [Errno 2] No such file or directory: 'pin_J/inscount.out'
I had exception [Errno 2] No such file or directory: 'pin_I/inscount.out'
sh: 1: /pin: not found
K had exception [Errno 2] No such file or directory: 'pin_K/inscount.out'
sh: 1: sh: 1: /pin: not found/pin: not found

sh: 1: /pin: not found
L had exception [Errno 2] No such file or directory: 'pin_L/inscount.out'
N had exception [Errno 2] No such file or directory: 'pin_N/inscount.out'
M had exception [Errno 2] No such file or directory: 'pin_M/inscount.out'
sh: 1: /pin: not found
O had exception [Errno 2] No such file or directory: 'pin_O/inscount.out'
sh: 1: /pin: not found
Q had exception [Errno 2] No such file or directory: 'pin_Q/inscount.out'
sh: 1: /pin: not found
P had exception [Errno 2] No such file or directory: 'pin_P/inscount.out'
sh: 1: /pin: not found
R had exception [Errno 2] No such file or directory: 'pin_R/inscount.out'
sh: 1: /pin: not found
S had exception [Errno 2] No such file or directory: 'pin_S/inscount.out'
sh: 1: /pin: not foundsh: 1:
/pin: not found
U had exception [Errno 2] No such file or directory: 'pin_U/inscount.out'
sh: 1: T had exception [Errno 2] No such file or directory: 'pin_T/inscount.out'
/pin: not found
V had exception [Errno 2] No such file or directory: 'pin_V/inscount.out'
sh: 1: /pin: not found
sh: 1: W had exception [Errno 2] No such file or directory: 'pin_W/inscount.out'
/pin: not found
sh: 1: /pin: not found
X had exception [Errno 2] No such file or directory: 'pin_X/inscount.out'
Z had exception [Errno 2] No such file or directory: 'pin_Z/inscount.out'
sh: 1: /pin: not found
Y had exception [Errno 2] No such file or directory: 'pin_Y/inscount.out'
sh: 1: /pin: not found
1 had exception [Errno 2] No such file or directory: 'pin_1/inscount.out'
sh: 1: /pin: not found
3 had exception [Errno 2] No such file or directory: 'pin_3/inscount.out'
sh: 1: /pin: not found
4 had exception [Errno 2] No such file or directory: 'pin_4/inscount.out'
sh: 1: /pin: not found
2 had exception [Errno 2] No such file or directory: 'pin_2/inscount.out'
sh: 1: /pin: not found
5 had exception [Errno 2] No such file or directory: 'pin_5/inscount.out'
sh: 1: /pin: not found
6 had exception [Errno 2] No such file or directory: 'pin_6/inscount.out'
sh: 1: /pin: not found
7 had exception [Errno 2] No such file or directory: 'pin_7/inscount.out'
sh: 1: /pin: not found
8 had exception [Errno 2] No such file or directory: 'pin_8/inscount.out'
sh: 1: /pin: not foundsh: 1:
/pin: not found
0 had exception [Errno 2] No such file or directory: 'pin_0/inscount.out'
9 had exception [Errno 2] No such file or directory: 'pin_9/inscount.out'
sh: 1: /pin: not found
_ had exception [Errno 2] No such file or directory: 'pin__/inscount.out'
sh: 1: /pin: not found
- had exception [Errno 2] No such file or directory: 'pin_-/inscount.out'
sh: 1: /pin: not found
@ had exception [Errno 2] No such file or directory: 'pin_@/inscount.out'
Traceback (most recent call last):
  File "pinCTF.py", line 439, in <module>
    main()
  File "pinCTF.py", line 103, in main
    pattern = pinIter(pinLocation,libraryLocation,args.file,seed,variable_range,arg=False,start=start,threading=threading,threadCount=int(args.threadCount),reverseRange=args.reversed,skip=args.skip)
  File "pinCTF.py", line 329, in pinIter
    average = sum(rangeList) / float(len(rangeList))
ZeroDivisionError: float division by zero

**Comment by neomh** [comment]
issue happens only when using threading...

**Comment by ChrisTheCoolHut** [comment]
I can't get this to replicate:
![image](https://user-images.githubusercontent.com/10480015/38044278-4443a1c4-3287-11e8-8537-685d1a2d5b28.png)
Can you make sure ELF-NoSoftwareBreakpoints is executable and whether this works without running as sudo?
