### ISSUE TITLE
can you open the source code of the examples

### ISSUE THREAD

**Issue by zaxfenfeiyu** [ChrisTheCoolHut/PinCTF#7]
When I try to use the -il to get my program's password length, it doesn't work.
I don't know these examples use which way to compare strings.
So can you open the souce code of these examples, thanks very much.

**Comment by ChrisTheCoolHut** [comment]
test.c
gcc test.c -o test -m32

> #include <string.h>
> #include <stdlib.h>
> #include <stdio.h>
> 
> void main (int argc, char *argv[])
> {
> 	if(argc != 2) exit(0);
> 	
> 	if(strcmp(argv[1],"SecretPassword") == 0)
> 	{
> 		printf("[+] You got the secret password!\n");
> 		exit(0);
> 	}
> 	printf("[-] Wrong\n");
> 	exit(0);
> }

>  chris@Computer:~/PinCTF$ ./pinCTF.py -f test -a -sl 14 -t -tc 22
> [~] Status:
> threading : True
> reverseRange : False
> skipFavoredPaths : False
> [+] iter 0 using S for SAAAAAAAAAAAAA
> [+] iter 1 using e for SeAAAAAAAAAAAA
> [+] iter 2 using c for SecAAAAAAAAAAA
> [~] Largest instruction count found to match several others or very close
> [~] Locating largest difference from average instead
> [~] Adding delta favored path SecsAAAAAAAAAA
> [~] Adding delta favored path SecyAAAAAAAAAA
> [~] Adding delta favored path SecuAAAAAAAAAA
> [~] Adding delta favored path SecxAAAAAAAAAA
> [~] Adding delta favored path SecwAAAAAAAAAA
> [~] Adding delta favored path SectAAAAAAAAAA
> [~] Adding delta favored path SeczAAAAAAAAAA
> [~] Adding delta favored path SecvAAAAAAAAAA
> [+] iter 3 using r for SecrAAAAAAAAAA
> [-] Single unique instruction count
> [~] Switching to other favored paths
> Removing SectAAAAAAAAAA
> Multiple FavoredPaths : 8
> SecwAAAAAAAAAA
> SecvAAAAAAAAAA
> SeczAAAAAAAAAA
> SecyAAAAAAAAAA
> SecrAAAAAAAAAA
> SecxAAAAAAAAAA
> SecsAAAAAAAAAA
> SecuAAAAAAAAAA
> [+] Ignoring path SectAAAAAAAAAA
> [-] Single unique instruction count
> [~] Switching to other favored paths
> Removing SecwAAAAAAAAAA
> Multiple FavoredPaths : 7
> SecvAAAAAAAAAA
> SeczAAAAAAAAAA
> SecyAAAAAAAAAA
> SecrAAAAAAAAAA
> SecxAAAAAAAAAA
> SecsAAAAAAAAAA
> SecuAAAAAAAAAA
> [+] Ignoring path SecwAAAAAAAAAA
> [-] Single unique instruction count
> [~] Switching to other favored paths
> Removing SecvAAAAAAAAAA
> Multiple FavoredPaths : 6
> SeczAAAAAAAAAA
> SecyAAAAAAAAAA
> SecrAAAAAAAAAA
> SecxAAAAAAAAAA
> SecsAAAAAAAAAA
> SecuAAAAAAAAAA
> [+] Ignoring path SecvAAAAAAAAAA
> [-] Single unique instruction count
> [~] Switching to other favored paths
> Removing SeczAAAAAAAAAA
> Multiple FavoredPaths : 5
> SecyAAAAAAAAAA
> SecrAAAAAAAAAA
> SecxAAAAAAAAAA
> SecsAAAAAAAAAA
> SecuAAAAAAAAAA
> [+] Ignoring path SeczAAAAAAAAAA
> [-] Single unique instruction count
> [~] Switching to other favored paths
> Removing SecyAAAAAAAAAA
> Multiple FavoredPaths : 4
> SecrAAAAAAAAAA
> SecxAAAAAAAAAA
> SecsAAAAAAAAAA
> SecuAAAAAAAAAA
> [+] Ignoring path SecyAAAAAAAAAA
> [+] iter 4 using e for SecreAAAAAAAAA
> [-] Single unique instruction count
> [~] Switching to other favored paths
> Removing SecxAAAAAAAAAA
> [-] Error path already gone
> [+] Ignoring path SecxAAAAAAAAAA
> [-] Single unique instruction count
> [~] Switching to other favored paths
> Removing SecsAAAAAAAAAA
> [-] Error path already gone
> [+] Ignoring path SecsAAAAAAAAAA
> [-] Single unique instruction count
> [~] Switching to other favored paths
> Removing SecuAAAAAAAAAA
> [-] Error path already gone
> [+] Ignoring path SecuAAAAAAAAAA
> [+] iter 5 using t for SecretAAAAAAAA
> [+] iter 6 using P for SecretPAAAAAAA
> [~] Largest instruction count found to match several others or very close
> [~] Locating largest difference from average instead
> [+] iter 7 using a for SecretPaAAAAAA
> [+] iter 8 using s for SecretPasAAAAA
> [+] iter 9 using s for SecretPassAAAA
> [+] iter 10 using w for SecretPasswAAA
> [+] iter 11 using o for SecretPasswoAA
> [+] iter 12 using r for SecretPassworA
> [+] iter 13 using d for SecretPassword
> [+] Found pattern SecretPassword
>
